### ISSUE TITLE
Link HydPy group

### ISSUE THREAD

**Issue by bkamapantula** [HydPy/pyconfhyd2025#13]
Need to promote HydPy User group on the conference website: https://www.hydpy.org/

**Comment by RajatRajdeep** [comment]
**Add 'Meet The Organizers' Section Below Hero Banner**

Please add a new UI element section below the Hero Banner with the following details:
- Section Title: Meet The Organizers
- Content
- Logo
- Hyperlink: https://www.hydpy.org/
  
The content to be included is as follows, but final review can be done by @bkamapantula on PR:
_Hyderabad Python User Group (HydPy) is community driven group to promote Python in Hyderabad. HydPy has been conducting monthly Meetups & workshops in Hyderabad for last 7+ years and it has over 15000 members on meetup. We work together with other communities in particular, python and in general Open Source Software (OSS) related groups within Hyderabad and the rest of India to further expand the usage and increase users of OSS. HydPy is a recognised regional community by global Python Software Foundation (PSF)._
Reference: [PyConf HydPy 2020 About](https://pyconf.hydpy.org/2020/about.html)

**Note**:
- The number of years should be verified for accuracy.
- Feel free to suggest/make UI changes.

**Comment by RajatRajdeep** [comment]
Here's the logo svg which can be added.
![HydPy](https://github.com/user-attachments/assets/51bf3139-445c-4e2e-84dd-b9d5d992b40a)

**Comment by kalyan678** [comment]
@RajatRajdeep The number of years should be 9 . I see we have created the group in 2016 so this matches with the number I mentioned.
@vamc-k I think we are good to add the details in the website.

At the moment I do not have any thoughts on UI but will share eventually!!

**Comment by vamc-k** [comment]
@kalyan678 @RajatRajdeep Can I get hydpy logo file. Couldn't able to download above file.

**Comment by RajatRajdeep** [comment]
@vamc-k,
HydPy Logo file link: https://drive.google.com/file/d/1YZclBmOh4PBhprttJAQ4CD7mj3LPGHvJ/view
