### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by bhansa** [HydPy/pyconfhyd2025#20]
Add a favicon for website

**Comment by shivkatira** [comment]
@bhansa I would like to work on this.

**Comment by shivkatira** [comment]
@bhansa where can I find favicon file?

**Comment by bhansa** [comment]
Sure, please use the updated logo. Also join the discord server for pyconf 2025

**Comment by shivkatira** [comment]
@bhansa could you please share discord server invite link?

**Comment by bhansa** [comment]
https://discord.gg/MR8jrpX4
