### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by RajatRajdeep** [HydPy/pyconfhyd2025#27]
The design team made minor changes to the logo, but the updated version has not been added yet.
You can find the latest logo here: [logo](https://github.com/HydPy/pyconfhyd25-tasks/tree/main/logo)

**Comment by kalyan678** [comment]
@RajatRajdeep - I think we are good to close this one right?

**Comment by RajatRajdeep** [comment]
This is to be updated. I’ll assign it to myself and close ASAP.
