### ISSUE TITLE
Dark mode 

### ISSUE THREAD

**Issue by RajatRajdeep** [HydPy/pyconfhyd2025#4]
Tailwind CSS is utilized in this project. Changes are needed in:
* [Theme configuration](https://github.com/HydPy/pyconfhyd2025/blob/main/tailwind.config.js)
* [Components](https://github.com/HydPy/pyconfhyd2025/tree/main/src/components)

For reference, see [Tailwind CSS Dark Mode documentation](https://tailwindcss.com/docs/dark-mode).

**Comment by shivkatira** [comment]
@RajatRajdeep I would like to work on this issue.

**Comment by shivkatira** [comment]
@RajatRajdeep Please share [monumentsSketch](https://github.com/HydPy/pyconfhyd2025/blob/main/public/images/monumentsSketch.svg) for the dark mode.

**Comment by shivkatira** [comment]
> @RajatRajdeep Please share [monumentsSketch](https://github.com/HydPy/pyconfhyd2025/blob/main/public/images/monumentsSketch.svg) for the dark mode.

@RajatRajdeep edited the svg file, no need to share the image.
